TP 466070 - [USD I/O] Fix the exception caused by SNAC when exporting to USD.
Summary:
When attempting to bake out a UsdMaterialBake with a network that includes a ShadingNodeArrayConnector node (SNAC) the bake operation fails and the following is output to the message log  and console. A standard LookfileBake is working correctly. Demo in attached video

```A LookFileBakeException occurred in "LookFileBaker.py": Error writing UsdExport look file: 'NoneType' object has no attribute 'GetTypeAsSdfType'    root    2021-01-28T11:14:41
Traceback (most recent call last):
  File "C:\Program Files\Foundry\Katana4.0dev.000642a\plugins\Resources\Usd\plugin\SuperTools\UsdMaterialBake\Editor.py", line 93, in <lambda>
    lambda checked : self.__groupNode.bake(parentWidget=self))
  File "C:\Program Files\Foundry\Katana4.0dev.000642a\plugins\Resources\Usd\plugin\SuperTools\UsdMaterialBake\Node.py", line 270, in bake
    referenceOp, passNamesAndOps, rootLocations, assetId)
  File "LookFileBaker.py", line 347, in bakeAndPublish
  File "LookFileBaker.py", line 651, in bake
LookFileBakeException: Error writing UsdExport look file: 'NoneType' object has no attribute 'GetTypeAsSdfType'```